mapper = {
'Afghanistan':	['Dari Persian', 'Pashtu'],
'Albania': ['Albanian', 'Tosk', 'Greek'],
'Algeria':	['Arabic', 'French', 'Berber dialects'],
'Andorra': ['Catalán', 'French', 'Castilian', 'Portuguese'],
'Angola':	['Portuguese', 'Bantu'],
'Antigua and Barbuda':	['English'],
'Argentina': ['Spanish', 'English', 'Italian', 'German', 'French'],
'Armenia': ['Armenian', 'Yezidi', 'Russian'],
'Australia': ['English'],
'Austria': ['German', 'Slovene', 'Croatian', 'Hungarian'],
'Azerbaijan': ['Azerbaijani', 'Turkic', 'Russian', 'Armenian'],
'Bahamas': ['English', 'Creole'],
'Bahrain': ['Arabic', 'English', 'Farsi', 'Urdu'],
'Bangladesh': ['Bangla', 'English'],
'Barbados':	['English'],
'Belarus': ['Belorussian', 'Russian'],
'Belgium': ['Dutch', 'French', 'German'],
'Belize': ['English', 'Spanish', 'Mayan', 'Garifuna', 'Creole'],
'Benin': ['French', 'Fon', 'Yoruba'],
'Bhutan': ['Dzongkha', 'Tibetan dialects', 'Nepalese dialects'],
'Bolivia': ['Spanish', 'Quechua', 'Aymara'],
'Bosnia and Herzegovina': ['Bosnian', 'Croatian', 'Serbian'],
'Botswana':	['English', 'Setswana', 'Kalanga', 'Sekgalagadi'],
'Brazil': ['Portuguese', 'Spanish', 'English', 'French'],
'Brunei': ['Malay', 'English', 'Chinese'],
'Bulgaria':	['Bulgarian', 'Turkish', 'Roma'],
'Burkina Faso':	['French'],
'Burundi': ['Kirundi', 'French', 'Swahili'],
'Cambodia': ['Khmer', 'French', 'English'],
'Cameroon': ['French', 'English'],
'Canada': ['English', 'French'],
'Cape Verde': ['Portuguese', 'Criuolo'],
'Central African Republic':	['French', 'Sangho'],
'Chad':	['French', 'Arabic', 'Sara'],
'Chile': ['Spanish'],
'China': ['Mandarin', 'Yue', 'Wu', 'Minbei', 'Minnan', 'Xiang', 'Gan'],
'Colombia': ['Spanish'],
'Comoros': ['Arabic', 'French', 'Shikomoro', 'Swahili'],
'Congo, Democratic Republic': ['French', 'Lingala', 'Kingwana', 'Kikongo', 'Tshiluba'],
'Congo, Republic': ['French', 'Lingala', 'Monokutuba', 'Kikongo'],
'Costa Rica': ['Spanish', 'English'],
"Côte d'Ivoire": ['French', 'Dioula'],
'Croatia': ['Croatian', 'Italian', 'Hungarian', 'Czech', 'Slovak', 'German'],
'Cuba': ['Spanish'],
'Cyprus': ['Greek', 'Turkish', 'English'],
'Czech Republic': ['Czech'],
'Denmark': ['Danish', 'Faroese', 'Greenlandic', 'German', 'English'],
'Djibouti':	['French', 'Arabic', 'Somali', 'Afar'],
'Dominica':	['English', 'French'],
'Dominican Republic': ['Spanish'],
'East Timor': ['Tetum', 'Portuguese', 'Bahasa Indonesia', 'English', 'Galole', 'Mambae', 'Kemak'],
'Ecuador': ['Spanish', 'Quechua'],
'Egypt': ['Arabic', 'English', 'French'],
'El Salvador': ['Spanish', 'Nahua'],
'Equatorial Guinea': ['Spanish', 'French' 'Fang', 'Bubi', 'Igbo'],
'Eritrea': ['Afar', 'Arabic', 'Tigre', 'Kunama', 'Tigrinya'],
'Estonia': ['Estonian', 'Russian'],
'Ethiopia':	['Amharic', 'Tigrigna', 'Orominga', 'Guaragigna', 'Somali', 'Arabic', 'English'],
'Fiji':	['English', 'Fijian', 'Hindustani'],
'Finland': ['Finnish', 'Swedish'],
'France': ['French'],
'Gabon': ['French', 'Fang', 'Myene', 'Nzebi', 'Bapounou', 'Bandjabi'],
'Gambia': ['English', 'Mandinka', 'Wolof', 'Fula'],
'Georgia': ['Georgian', 'Russian', 'Armenian', 'Azerbaijani', 'Abkhaz'],
'Germany': ['German'],
'Ghana': ['English', 'Akan', 'Moshi-Dagomba', 'Ewe', 'Ga'],
'Greece': ['Greek', 'English', 'French'],
'Grenada': ['English', 'French'],
'Guatemala': ['Spanish', 'Quiche', 'Cakchiquel', 'Kekchi', 'Mam', 'Garifuna', 'Xinca'],
'Guinea': ['French', 'Malinké', 'Susu', 'Fulani'],
'Guinea-Bissau': ['Portuguese', 'Criolo'],
'Guyana': ['English', 'Creole', 'Hindi', 'Urdu'],
'Haiti': ['Creole', 'French'],
'Honduras':	['Spanish', 'English'],
'Hungary': ['Magyar'],
'Iceland': ['Icelandic', 'English', 'German'],
'India': ['Hindi', 'English', 'Bengali', 'Gujarati', 'Kashmiri', 'Malayalam', 'Marathi', 'Oriya', 'Punjabi', 'Tamil', 'Telugu', 'Urdu', 'Kannada', 'Assamese', 'Sanskrit', 'Sindhi'],
'Indonesia': ['Bahasa Indonesia', 'English', 'Dutch', 'Javanese'],
'Iran':	['Persian', 'Turkic', 'Kurdish', 'Luri', 'Balochi', 'Arabic', 'Turkish'],
'Iraq':	['Arabic', 'Kurdish', 'Assyrian', 'Armenian'],
'Ireland': ['English', 'Irish'],
'Israel': ['Hebrew', 'Arabic', 'English'],
'Italy': ['Italian', 'German', 'French', 'Slovene'],
'Jamaica': ['English', 'Jamaican' 'Creole'],
'Japan': ['Japanese'],
'Jordan': ['Arabic', 'English'],
'Kazakhstan': ['Kazak', 'Russian',],
'Kenya': ['English', 'Swahili'],
'Kiribati':	['English', 'I-Kiribati'],
'North Korea': ['Korean'],
'South Korea': ['Korean', 'English'],
'Kosovo': ['Albanian', 'Serbian', 'Bosnian', 'Turkish', 'Roma'],
'Kuwait': ['Arabic', 'English'],
'Kyrgyzstan': ['Kyrgyz', 'Russian'],
'Laos':	['Lao', 'French', 'English'],
'Latvia': ['Latvian', 'Russian', 'Lithuanian'],
'Lebanon': ['Arabic', 'French', 'English', 'Armenian'],
'Lesotho': ['English', 'Sesotho'],
'Liberia': ['English'],
'Libya': ['Arabic', 'Italian', 'English'],
'Liechtenstein': ['German', 'Alemannic'],
'Lithuania': ['Lithuanian', 'Russian', 'Polish'],
'Luxembourg': ['Luxermbourgish', 'French', 'German'],
'Macedonia': ['Macedonian', 'Albanian', 'Turkish', 'Roma', 'Serbian'],
'Madagascar': ['Malagasy', 'French'],
'Malawi': ['Chichewa', 'Chinyanja', 'Chiyao', 'Chitumbuka', 'Chisena', 'Chilomwe', 'Chitonga'],
'Malaysia':	['Bahasa Melayu', 'English', 'Mandarin', 'Tamil', 'Telugu', 'Malayalam', 'Panjabi', 'Thai' 'Iban', 'Kadazan'],
'Maldives':	['Maldivian' 'Dhivehi', 'English'],
'Mali':	['French', 'Bambara'],
'Malta': ['Maltese', 'English'],
'Marshall Islands':	['Marshallese', 'English', 'Japanese'],
'Mauritania': ['Hassaniya', 'Arabic', 'Pulaar', 'Soninke', 'French', 'Wolof'],
'Mauritius': ['English', 'Creole', 'Bojpoori', 'French'],
'Mexico': ['Spanish'],
'Micronesia': ['English', 'Chukese', 'Pohnpeian', 'Yapase', 'Kosrean', 'Ulithian', 'Woleaian', 'Nukuoro', 'Kapingamarangi'],
'Moldova': ['Moldovan', 'Russian', 'Gagauz'],
'Monaco': ['French', 'English', 'Italian', 'Monégasque'],
'Mongolia':	['Mongolian', 'Turkic', 'Russian'],
'Montenegro': ['Serbian', 'Ijekavian'],
'Morocco': ['Arabic', 'Berber', 'French'],
'Mozambique': ['Portuguese', 'Emakhuwa', 'Xichangana', 'Elomwe', 'Cisena', 'Echuwabo'],
'Myanmar': ['Burmese'],
'Namibia': ['English', 'Afrikaans', 'German', 'Oshivambo', 'Herero', 'Nama'],
'Nauru': ['Nauruan', 'English'],
'Nepal': ['Nepali', 'Maithali', 'Bhojpuri', 'Tharu', 'Tamang', 'English'],
'Netherlands': ['Dutch', 'Frisian'],
'New Zealand': ['English', 'Maori'],
'Nicaragua': ['Spanish', 'English'],
'Niger': ['French', 'Hausa', 'Djerma'],
'Nigeria': ['English', 'Hausa', 'Yoruba', 'Igbo', 'Fulani'],
'Norway': ['Bokmål', 'Norwegian', 'Nynorsk', 'Norwegian', 'Sami'],
'Oman': ['Arabic', 'English', 'Baluchi', 'Urdu'],
'Pakistan': ['Urdu', 'English', 'Punjabi', 'Sindhi', 'Siraiki', 'Pashtu', 'Balochi', 'Hindko', 'Brahui', 'Burushaski'],
'Palau': ['Palauan', 'English', 'Sonsoralese', 'Tobi', 'Angaur', 'Filipino', 'Chinese', 'Carolinian', 'Japanese'],
'Palestinian': ['State', 'Arabic', 'Hebrew', 'English'],
'Panama': ['Spanish', 'English'],
'Papua New Guinea': ['Tok Pisin', 'Hiri Motu', 'English'],
'Paraguay': ['Spanish', 'Guaraní'],
'Peru': ['Spanish', 'Quéchua', 'Aymara'],
'Philippines': ['Filipino', 'English', 'Tagalog', 'Cebuano', 'Ilocano', 'Hiligaynon', 'Ilonggo', 'Bicol', 'Waray', 'Pampango', 'Pangasinense'],
'Poland': ['Polish'],
'Portugal': ['Portuguese', 'Mirandese'],
'Qatar': ['Arabic', 'English'],
'Romania': ['Romanian', 'Hungarian', 'German'],
'Russia': ['Russian'],
'Rwanda': ['Kinyarwanda', 'French', 'English', 'Swahili'],
'St. Kitts and Nevis': ['English'],
'St. Lucia': ['English', 'French'],
'St. Vincent and the Grenadines': ['English', 'French'],
'Samoa': ['Samoan', 'English'],
'San Marino': ['Italian'],
'São Tomé and Príncipe': ['Portuguese'],
'Saudi Arabia': ['Arabic'],
'Senegal': ['French', 'Wolof', 'Pulaar', 'Jola', 'Mandinka'],
'Serbia': ['Serbian', 'Romanian', 'Hungarian', 'Slovak', 'Croatian', 'Albanian'],
'Seychelles': ['Seselwa Creole', 'English', 'French'],
'Sierra Leone': ['English', 'Mende', 'Temne', 'Krio'],
'Singapore': ['Mandarin', 'English', 'Malay', 'Hokkien', 'Cantonese', 'Teochew', 'Tamil'],
'Slovakia': ['Slovak', 'Hungarian', 'Roma', 'Ukrainian'],
'Slovenia': ['Slovenian', 'Serbo-Croatian'],
'Solomon Islands': ['English', 'Melanesian'],
'Somalia': ['Somali', 'Arabic', 'English', 'Italian'],
'South Africa': ['IsiZulu', 'IsiXhosa', 'Afrikaans', 'Sepedi', 'English', 'Setswana', 'Sesotho', 'Xitsonga', 'Ndebele', 'Venda', 'siSwati'],
'South Sudan': ['English', 'Arabic', 'Juba', 'Sudanese', 'Dinka', 'Nuer', 'Bari', 'Zande', 'Shilluk'],
'Spain': ['Spanish', 'Catalan', 'Galician', 'Basque'],
'Sri Lanka': ['Sinhala', 'Tamil', 'English'],
'Sudan': ['Arabic', 'Nubian', 'Ta', 'Bedawie', 'Nilo-Hamitic', 'English'],
'Suriname': ['Dutch', 'Surinamese', 'English', 'Hindustani', 'Javanese'],
'Swaziland': ['English', 'siSwati'],
'Sweden': ['Swedish'],
'Switzerland': ['German', 'French', 'Italian', 'Romansch'],
'Syria': ['Arabic', 'Kurdish', 'Armenian', 'Aramaic', 'Circassian', 'French', 'English'],
'Taiwan': ['Mandarin', 'Taiwanese', 'Hakka'],
'Tajikistan': ['Tajik', 'Russian'],
'Tanzania': ['Swahili', 'English', 'Arabic'],
'Thailand': ['Thai', 'English'],
'Togo': ['French', 'Ewé', 'Mina', 'Kabyé', 'Dagomba'],
'Tonga': ['Tongan', 'English'],
'Trinidad and Tobago': ['English', 'Hindi', 'French', 'Spanish', 'Chinese'],
'Tunisia': ['Arabic', 'French'],
'Turkey': ['Turkish', 'Kurdish', 'Dimli', 'Azeri', 'Kabardian'],
'Turkmenistan': ['Turkmen', 'Russian', 'Uzbek'],
'Tuvalu': ['Tuvaluan', 'English', 'Samoan', 'Kiribati'],
'Uganda': ['English', 'Ganda', 'Luganda', 'Nilo-Saharan', 'Swahili', 'Arabic'],
'Ukraine': ['Ukrainian', 'Russian', 'Romanian', 'Polish', 'Hungarian'],
'United Arab Emirates': ['Arabic', 'Persian', 'English', 'Hindi', 'Urdu'],
'United Kingdom': ['English', 'Welsh', 'Scots Gaelic'],
'United States': ['English', 'Spanish'],
'Uruguay': ['Spanish', 'Portunol', 'Brazilero'],
'Uzbekistan': ['Uzbek', 'Russian', 'Tajik'],
'Vanuatu': ['Bislama', 'English', 'French'],
'Vatican City': ['Italian', 'Latin', 'French'],
'Venezuela': ['Spanish'],
'Vietnam': ['Vietnamese', 'English', 'French', 'Mandarin', 'Khmer'],
'Western Sahara': ['Hassaniya', 'Arabic'],
'Yemen': ['Arabic'],
'Zambia': ['English', 'Bemba', 'Kaonda', 'Lozi', 'Lunda', 'Luvale', 'Nyanja', 'Tonga'],
'Zimbabwe': ['English', 'Shona', 'Ndebele']
}

languages = ['Dari Persian', 'Pashtu', 'Albanian', 'Tosk', 'Greek', 'Arabic', 'French', 'Berber dialects', 'Catalán', 'Castilian', 'Portuguese', 'Bantu', 'English', 'Spanish', 'Italian', 'German', 'Armenian', 'Yezidi', 'Russian', 'Slovene', 'Croatian', 'Hungarian', 'Azerbaijani', 'Turkic', 'Creole', 'Farsi', 'Urdu', 'Bangla', 'Belorussian', 'Dutch', 'Mayan', 'Garifuna', 'Fon', 'Yoruba', 'Dzongkha', 'Tibetan dialects', 'Nepalese dialects', 'Quechua', 'Aymara', 'Bosnian', 'Serbian', 'Setswana', 'Kalanga', 'Sekgalagadi', 'Malay', 'Chinese', 'Bulgarian', 'Turkish', 'Roma', 'Kirundi', 'Swahili', 'Khmer', 'Criuolo', 'Sangho', 'Sara', 'Mandarin', 'Yue', 'Wu', 'Minbei', 'Minnan', 'Xiang', 'Gan', 'Shikomoro', 'Lingala', 'Kingwana', 'Kikongo', 'Tshiluba', 'Monokutuba', 'Dioula', 'Czech', 'Slovak', 'Danish', 'Faroese', 'Greenlandic', 'Somali', 'Afar', 'Tetum', 'Bahasa Indonesia', 'Galole', 'Mambae', 'Kemak', 'Nahua', 'FrenchFang', 'Bubi', 'Igbo', 'Tigre', 'Kunama', 'Tigrinya', 'Estonian', 'Amharic', 'Tigrigna', 'Orominga', 'Guaragigna', 'Fijian', 'Hindustani', 'Finnish', 'Swedish', 'Fang', 'Myene', 'Nzebi', 'Bapounou', 'Bandjabi', 'Mandinka', 'Wolof', 'Fula', 'Georgian', 'Abkhaz', 'Akan', 'Moshi-Dagomba', 'Ewe', 'Ga', 'Quiche', 'Cakchiquel', 'Kekchi', 'Mam', 'Xinca', 'Malinké', 'Susu', 'Fulani', 'Criolo', 'Hindi', 'Magyar', 'Icelandic', 'Bengali', 'Gujarati', 'Kashmiri', 'Malayalam', 'Marathi', 'Oriya', 'Punjabi', 'Tamil', 'Telugu', 'Kannada', 'Assamese', 'Sanskrit', 'Sindhi', 'Javanese', 'Persian', 'Kurdish', 'Luri', 'Balochi', 'Assyrian', 'Irish', 'Hebrew', 'JamaicanCreole', 'Japanese', 'Kazak', 'I-Kiribati', 'Korean', 'Kyrgyz', 'Lao', 'Latvian', 'Lithuanian', 'Sesotho', 'Alemannic', 'Polish', 'Luxermbourgish', 'Macedonian', 'Malagasy', 'Chichewa', 'Chinyanja', 'Chiyao', 'Chitumbuka', 'Chisena', 'Chilomwe', 'Chitonga', 'Bahasa Melayu', 'Panjabi', 'ThaiIban', 'Kadazan', 'MaldivianDhivehi', 'Bambara', 'Maltese', 'Marshallese', 'Hassaniya', 'Pulaar', 'Soninke', 'Bojpoori', 'Chukese', 'Pohnpeian', 'Yapase', 'Kosrean', 'Ulithian', 'Woleaian', 'Nukuoro', 'Kapingamarangi', 'Moldovan', 'Gagauz', 'Monégasque', 'Mongolian', 'Ijekavian', 'Berber', 'Emakhuwa', 'Xichangana', 'Elomwe', 'Cisena', 'Echuwabo', 'Burmese', 'Afrikaans', 'Oshivambo', 'Herero', 'Nama', 'Nauruan', 'Nepali', 'Maithali', 'Bhojpuri', 'Tharu', 'Tamang', 'Frisian', 'Maori', 'Hausa', 'Djerma', 'Bokmål', 'Norwegian', 'Nynorsk', 'Sami', 'Baluchi', 'Siraiki', 'Hindko', 'Brahui', 'Burushaski', 'Palauan', 'Sonsoralese', 'Tobi', 'Angaur', 'Filipino', 'Carolinian', 'State', 'Tok Pisin', 'Hiri Motu', 'Guaraní', 'Quéchua', 'Tagalog', 'Cebuano', 'Ilocano', 'Hiligaynon', 'Ilonggo', 'Bicol', 'Waray', 'Pampango', 'Pangasinense', 'Mirandese', 'Romanian', 'Kinyarwanda', 'Samoan', 'Jola', 'Seselwa Creole', 'Mende', 'Temne', 'Krio', 'Hokkien', 'Cantonese', 'Teochew', 'Ukrainian', 'Slovenian', 'Serbo-Croatian', 'Melanesian', 'IsiZulu', 'IsiXhosa', 'Sepedi', 'Xitsonga', 'Ndebele', 'Venda', 'siSwati', 'Juba', 'Sudanese', 'Dinka', 'Nuer', 'Bari', 'Zande', 'Shilluk', 'Catalan', 'Galician', 'Basque', 'Sinhala', 'Nubian', 'Ta', 'Bedawie', 'Nilo-Hamitic', 'Surinamese', 'Romansch', 'Aramaic', 'Circassian', 'Taiwanese', 'Hakka', 'Tajik', 'Thai', 'Ewé', 'Mina', 'Kabyé', 'Dagomba', 'Tongan', 'Dimli', 'Azeri', 'Kabardian', 'Turkmen', 'Uzbek', 'Tuvaluan', 'Kiribati', 'Ganda', 'Luganda', 'Nilo-Saharan', 'Welsh', 'Scots Gaelic', 'Portunol', 'Brazilero', 'Bislama', 'Latin', 'Vietnamese', 'Bemba', 'Kaonda', 'Lozi', 'Lunda', 'Luvale', 'Nyanja', 'Tonga', 'Shona']